newroadsmedia_frontend:
    resource: ../../../src/NewRoadsMedia/FrontendBundle/Controller
    type:     annotation

# Sonata Admin
admin:
    resource: @SonataAdminBundle/Resources/config/routing/sonata_admin.xml
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

gregwar_captcha_routing:
    resource: @GregwarCaptchaBundle/Resources/config/routing/routing.yml
    schemes: [https]
    prefix: /gcb