imports:
    - { resource: @NewRoadsMediaFrontendBundle/Resources/config/admin.yml }

sonata_admin:
    title: %site_title% Admin Panel
    options:
        title_mode: single_text
    dashboard:
        blocks:
            - { position: left, type: sonata.admin.block.admin_list }
            - { position: right, type: sonata.block.quick_links }
    templates:
        layout: NewRoadsMediaFrontendBundle:Admin:layout.html.twig

sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts:   [admin]
        sonata.block.quick_links: ~